### ISSUE TITLE
Hello，How to use NPM？

### ISSUE THREAD

**Issue by wphubs** [dobromir-hristov/fullpage-nuxt-module#1]
How to use NPM？

**Comment by dobromir-hristov** [comment]
Hey, this is just an experiment, and as you see not yet an npm package. You can however copy the modules on your local machine and try it out :) lmk if it works.

**Comment by wphubs** [comment]
ok，tks

**Comment by BlackBiM123** [comment]
hello, i have the same problem with full page on prod as you, i suppose. have you tried Dobromir's solution?

**Comment by BlackBiM123** [comment]
@w405287435  hello, i have the same problem with full page on prod as you, i suppose. have you tried Dobromir's solution?

**Comment by wphubs** [comment]
@BlackBiM123   No，I haven't solved。I'm waiting for fullpage.js next version

**Comment by BlackBiM123** [comment]
@w405287435 thx, i think i'll have to wait too, or try searching another plugin/ cause this solution didnt help me. just added more errors =(
though  there is a great chance that I'm doing something wrong. =)

**Comment by dobromir-hristov** [comment]
So there are a few things to this.

The `index.js` imports two files, a client and a server file. the Clinet is just a normal vue-fullpage init, where as the server, imports a pretty simple fullpage wrapper, that is used instead of importing fullpage on the server, as we know that doesnt work.

You can do the same and it should work :) I am waiting on Alvaro to approve this, so we can release it as a package or something.

**Comment by wphubs** [comment]
@BlackBiM123  My problem is NUXT.js  SSR， If you don't need to SEO，You can try   “no-ssr”  ，  it  can works

**Comment by w405287435** [comment]
no-ssr

**Comment by BlackBiM123** [comment]
@w405287435  mine too. i need ssr working properly
